plugin: amazon.aws.aws_ec2

regions:
  - "{{ lookup('env', 'AWS_REGION') | default('us-east-1', true) }}"

filters:
  tag:Project: challenge3
  instance-state-name: running

hostnames:
  - instance-id

compose:
  ansible_host: instance_id
  ansible_connection: "'amazon.aws.aws_ssm'"

keyed_groups:
  - key: ec2_tags.Server
    prefix: server