plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Project: challenge3
  instance-state-name: running
hostnames:
  - instance-id
compose:
  ansible_host: instance_id
  ansible_connection: "'aws_ssm'"
  ansible_aws_ssm_bucket_name: "'challenge3-web-421438965568'"
  ansible_aws_ssm_region: "'us-east-1'"
keyed_groups:
  - key: tags.Server
    prefix: server